// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBii_0hR2X0F_TgL3Hg0DQpVy4Sabr7npc',
    appId: '1:7946908578:web:e1013403254d7e673378fb',
    messagingSenderId: '7946908578',
    projectId: 'fleshchatkg',
    authDomain: 'fleshchatkg.firebaseapp.com',
    storageBucket: 'fleshchatkg.appspot.com',
    measurementId: 'G-Z2W209MXVX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCna4a4Rv6W62k-6Ua7HgLJN0YWwoPc8NY',
    appId: '1:7946908578:android:e4883e24b834a06b3378fb',
    messagingSenderId: '7946908578',
    projectId: 'fleshchatkg',
    storageBucket: 'fleshchatkg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6YJto_E9Dh6HelAri2KdbVibTUKQ8Epc',
    appId: '1:7946908578:ios:75bc5c429da256693378fb',
    messagingSenderId: '7946908578',
    projectId: 'fleshchatkg',
    storageBucket: 'fleshchatkg.appspot.com',
    iosClientId: '7946908578-k2a15r6j1434ln6fghp0q6rkakr91r92.apps.googleusercontent.com',
    iosBundleId: 'com.example.fleshchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6YJto_E9Dh6HelAri2KdbVibTUKQ8Epc',
    appId: '1:7946908578:ios:48552d9f47e0d86c3378fb',
    messagingSenderId: '7946908578',
    projectId: 'fleshchatkg',
    storageBucket: 'fleshchatkg.appspot.com',
    iosClientId: '7946908578-e9ckeevjir5av7qni6tsrhk46hvbhqha.apps.googleusercontent.com',
    iosBundleId: 'com.example.fleshchat.RunnerTests',
  );
}
